import type { Express } from "express";

/**
 * A route index that cannot go out of date.
 *
 * Checking whether an endpoint is live used to mean guessing its path from
 * memory, which risks reading a wrong guess as a broken service. This lists
 * what is actually mounted.
 *
 * The list is generated by walking Express's own router, not written out by
 * hand — a hand-written list is the thing that drifts, and a route index that
 * has drifted is worse than none, because it is believed. Adding a route to
 * the app adds it here with no further action.
 *
 * The one hand-maintained part is the prose: Express has nowhere to hang a
 * description, so the sentences live in the map below, keyed by method and
 * path. That cannot silently drift either — a route with no entry is still
 * listed, marked as undocumented, and a test fails until somebody writes the
 * sentence. So the failure mode is a visible gap rather than a missing route.
 */

export interface RouteInfo {
  method: string;
  path: string;
  description: string;
  /** False when this route has no description yet. */
  documented: boolean;
}

/**
 * One line per route, keyed by "METHOD /path" exactly as Express reports it.
 *
 * MAINTAINED BY HAND. Adding a route does not require touching this — the
 * route will appear in the index regardless — but `routes.test.ts` fails until
 * a description exists for it.
 */
export const ROUTE_DESCRIPTIONS: Record<string, string> = {
  "GET /api": "This index: every mounted route, with a one-line description.",
  "GET /api/routes": "Alias of GET /api.",
  "GET /api/health": "Liveness check. Returns ok and the server's clock.",

  "GET /api/groups":
    "The catalogue of satellite groups the picker is built from, and the cap on how many objects a pass search will scan.",
  "GET /api/satellites/search":
    "Search the catalogue by name via Celestrak's NAME query. Requires ?q= of at least 3 characters.",
  "GET /api/tle/:group":
    "Orbital elements for one named group. Optional ?limit= keeps only the brightest, for callers that only intend to draw them.",
  "GET /api/tle/satellite/:catnr":
    "Orbital elements for one satellite by NORAD catalogue number. 404 means the object is not in the catalogue, which usually means it has reentered.",

  "GET /api/passes":
    "Visible passes for an observer. Requires ?lat= and ?lon=; optional ?groups=, ?days=, ?minEl=, ?maxMag=, ?satnum=, ?weather=0.",
  "POST /api/passes/custom":
    "Visible passes for caller-supplied element sets, for satellites outside the tracked groups.",

  "GET /api/debris/catalogue":
    "The debris screen's two collections: named breakup clouds, and notable derelicts resolved individually so a vanished catalogue number is reported per object.",
  "GET /api/debris/cloud/:id":
    "Every catalogued fragment of one breakup cloud. Thousands of objects — requested explicitly, never loaded by default.",

  "GET /api/small-bodies":
    "Orbital elements for comets and asteroids bright enough to look for, from JPL's Small-Body Database.",
  "GET /api/radio/:catnr":
    "Amateur radio services for a satellite, from the SatNOGS register. An empty list means no known active downlink.",
  "GET /api/starlink/trains":
    "Starlink satellites still flying in formation close enough to be seen as a train.",
  "GET /api/earth-imagery":
    "The most recent full-disc image from whichever geostationary weather satellite best sees the observer's longitude.",
  "GET /api/aircraft":
    "Live ADS-B aircraft near the observer, from whichever provider answers first.",

  "GET /api/ai/status": "Whether the AI-backed endpoints below are configured and available.",
  "POST /api/explain": "AI explanation of an object in the sky. Rate limited.",
  "POST /api/orbit-advice": "AI orbit and mission-profile advice. Rate limited.",
};

/**
 * Express 4 keeps its route table on `app._router`, which is private and not
 * part of the documented surface. It is stable across the 4.x line, but if a
 * future version moves it this returns an empty list rather than throwing —
 * and the endpoint then reports plainly that it could not read the table,
 * instead of implying the server has no routes.
 */
interface ExpressLayer {
  route?: {
    path: string | string[];
    methods: Record<string, boolean>;
  };
}

export function collectRoutes(app: Express): RouteInfo[] {
  const stack: ExpressLayer[] | undefined = (
    app as unknown as { _router?: { stack?: ExpressLayer[] } }
  )._router?.stack;
  if (!Array.isArray(stack)) return [];

  const routes: RouteInfo[] = [];
  for (const layer of stack) {
    if (!layer.route) continue;
    const paths = Array.isArray(layer.route.path) ? layer.route.path : [layer.route.path];
    for (const path of paths) {
      for (const [method, enabled] of Object.entries(layer.route.methods)) {
        // Express records a HEAD alongside every GET; listing both would double
        // the index without telling anybody anything.
        if (!enabled || method === "head" || method === "_all") continue;
        const key = `${method.toUpperCase()} ${path}`;
        const description = ROUTE_DESCRIPTIONS[key];
        routes.push({
          method: method.toUpperCase(),
          path,
          description: description ?? "No description yet — see ROUTE_DESCRIPTIONS in server/src/routes.ts.",
          documented: description !== undefined,
        });
      }
    }
  }

  // Plain codepoint order, not localeCompare: that is locale-dependent, and a
  // server's ICU data need not match a laptop's, so the same build could order
  // its own index differently in production than in the test that checked it.
  return routes.sort((a, b) => {
    const left = `${a.method} ${a.path}`;
    const right = `${b.method} ${b.path}`;
    return left < right ? -1 : left > right ? 1 : 0;
  });
}

export interface RouteIndex {
  service: string;
  /** The canonical production host, so a reader knows they are on the right one. */
  canonicalHost: string;
  count: number;
  /** Routes mounted but not yet described. Zero in a healthy build. */
  undocumentedCount: number;
  routes: RouteInfo[];
  note?: string;
}

/**
 * The canonical production host for this service.
 *
 * Stated in the response because the confusion this index exists to end is
 * partly about which host you are talking to: `lookup-server.vercel.app`
 * without the suffix belongs to somebody else on Vercel's shared subdomain
 * namespace, and will answer with something that is not this app. Seeing this
 * field come back is how you know you reached ours. See DEPLOYMENT.md.
 */
export const CANONICAL_HOST = "lookup-server-sand.vercel.app";

export function buildRouteIndex(app: Express): RouteIndex {
  const routes = collectRoutes(app);
  const undocumentedCount = routes.filter((r) => !r.documented).length;

  return {
    service: "lookup-server",
    canonicalHost: CANONICAL_HOST,
    count: routes.length,
    undocumentedCount,
    routes,
    note:
      routes.length === 0
        ? "The route table could not be read from this Express version. This is a bug in the index, not an empty server."
        : undefined,
  };
}
