/**
 * Produces the Vercel serverless function entry (server/api/index.js).
 *
 * Vercel's own dependency bundler hits a real ESM/CJS dual-package hazard on
 * astronomy-engine (it resolves the package's ESM build but loads it through
 * a CommonJS loader, which throws on the bare `export` syntax). Pre-bundling
 * everything ourselves with esbuild sidesteps that entirely: esbuild resolves
 * and inlines each dependency's actual source once, at build time, so
 * Vercel's runtime never has to re-resolve astronomy-engine's package.json
 * exports itself.
 *
 * satellite.js is the one dependency left external rather than bundled: its
 * entry point re-exports an optional WASM/pthreads backend that uses
 * top-level await in a way esbuild can't statically bundle, and it isn't
 * needed — the pure-JS SGP4 API this app uses already resolves correctly at
 * runtime without bundling it (the client's Vite config stubs the same
 * barrel out for the same reason; see client/vite.config.ts).
 *
 * This used to be named api/[...path].js, relying on Vercel's catch-all
 * filename convention to route every /api/* request here with no
 * vercel.json needed. In practice that only matched a single path segment
 * beyond /api/ in this non-framework ("Other") project — /api/health
 * reached Express, /api/tle/stations 404'd at Vercel's own routing layer
 * before ever reaching the function. A plain filename plus an explicit
 * server/vercel.json "routes" rule (which selects the handler without
 * rewriting what the function itself receives) is what Express needs to do
 * its own routing correctly off the real request path.
 *
 * Local dev/build/start (tsx, tsc, dist/) are untouched; this only produces
 * an additional deployment artifact under server/api/.
 *
 * That artifact is committed to git rather than left gitignored: Vercel's
 * zero-config /api function discovery scans the source tree it clones from
 * git to decide what functions exist, before the "vercel-build" script (this
 * one) ever runs — a build-time-only output in api/ is silently never picked
 * up as a route. The committed copy exists purely so that discovery step
 * finds the route; its actual code is always freshly regenerated by this
 * script during the real build, so it can't go stale in what gets deployed.
 */
import { build } from 'esbuild';
import { mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const serverDir = dirname(dirname(fileURLToPath(import.meta.url)));
const outfile = join(serverDir, 'api', 'index.js');

mkdirSync(dirname(outfile), { recursive: true });

await build({
  entryPoints: [join(serverDir, 'src', 'index.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  external: ['satellite.js'],
  banner: {
    js: "import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);",
  },
});

console.log(`wrote ${outfile}`);
